package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.Entity;
import domain.EnumerationValue;

public class EnumerationValueRepository extends RepositoryBase<EnumerationValue> 
	implements IEnumerationValueRepository{

	public EnumerationValueRepository(Connection connection, 
			IMapResultSetToEntity<EnumerationValue> mapper,
			IUnitOfWork uow) {
		super(connection,mapper, uow);
	}

	public void setUpdateQuery(EnumerationValue ev) throws SQLException {
		update.setInt(1, ev.getIntKey());
		update.setString(2, ev.getStringKey());
		update.setString(3, ev.getValue());
		update.setString(4, ev.getEnumerationName());
		update.setInt(5, ev.getId());
	}

	public void setInsertQuery(EnumerationValue ev) throws SQLException {
		insert.setInt(1, ev.getIntKey());
		insert.setString(2, ev.getStringKey());
		insert.setString(3, ev.getValue());
		insert.setString(4, ev.getEnumerationName());
	}

	@Override
	protected String tableName() {
		return "t_sys_enums";
	}

	protected String createTableSql() {
		return "CREATE TABLE t_sys_enums("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "intKey int," + "stringKey VARCHAR(50)," + "value VARCHAR(50)," + "enumerationName VARCHAR(50)"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO t_sys_enums(intKey, stringKey, value, enumerationName ) VALUES (?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE t_sys_enums SET intKey = ?, stringKey = ?, value = ?, enumerationName = ? WHERE id = ?";
	}

	public List<EnumerationValue> withName (String name) {
	
		return null;
	}
	
	public List<EnumerationValue> withIntKey (int key, String name) {
		
		return null;
	}
	
	public List<EnumerationValue> withStringKey (String key, String name) {
		
		return null;
	}


}
