package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import dao.uow.IUnitOfWorkRepository;
import domain.UserRoles;
import domain.EnumerationValue;

public class UserRolesRepository extends RepositoryBase<UserRoles>
	implements IUserRolesRepository{

	public UserRolesRepository(Connection connection,
			IMapResultSetToEntity<UserRoles> mapper,
			IUnitOfWork uow) {
		super(connection, mapper, uow);
	}
	
	protected void setUpdateQuery(UserRoles ur) throws SQLException {
		update.setInt(1, ur.getUserId());
		update.setInt(2, ur.getRoleId());
		update.setInt(3, ur.getId());
	}
	
	protected void setInsertQuery(UserRoles ur) throws SQLException {
		insert.setInt(1, ur.getUserId());
		insert.setInt(2, ur.getRoleId());
	}
	
	@Override
	protected String tableName() {
		return "t_sys_roles";
	}
	@Override
	protected String createTableSql() {
		return 
				"CREATE TABLE t_sys_roles("
						+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
						+ "userId int,"
						+ "roleId int"			
						+ ")";
	}
	@Override
	protected String insertSql() {
		return 
				"INSERT INTO "
				+ "t_sys_roles(userId, roleId)"
				+ " VALUES (?,?)";
	}
	@Override
	protected String updateSql() {
		return "UPDATE t_sys_roles SET userId = ?, roleId = ? WHERE id = ?";
		
	}

	public List<UserRoles> withUserId(int userId) {

		return null;
	}
	
	public List<UserRoles> withRoleId(int roleId) {

		return null;
	}
	

	
}
